<script lang="ts">
  import { tooltip } from '$lib/actions/tooltip';
  import Icon from '$lib/components/global/Icon.svelte';
  import { t } from '$lib/stores/language';

  let hostnameInput = $state('');
  let ipInput = $state('');
  let ttl = $state(3600);
  let generateZoneFile = $state(false);
  let zoneName = $state('example.com');
  let results = $state<{ type: string; name: string; ttl: number; value: string }[]>([]);
  let zoneFileContent = $state('');
  let showExamples = $state(false);

  const examples = $derived([
    {
      label: $t('tools/dns-aaaa-bulk.examples.webServers'),
      hostnames: 'www\napi\ncdn\nstatic',
      ips: '192.168.1.10\n192.168.1.11\n192.168.1.12\n192.168.1.13',
    },
    {
      label: $t('tools/dns-aaaa-bulk.examples.mailServers'),
      hostnames: 'mail\nimap\nsmtp\npop3',
      ips: '10.0.1.20\n10.0.1.21\n10.0.1.22\n10.0.1.23',
    },
    {
      label: $t('tools/dns-aaaa-bulk.examples.ipv6Services'),
      hostnames: 'web6\napi6\nmail6',
      ips: '2001:db8::1\n2001:db8::2\n2001:db8::3',
    },
  ]);

  function isIPv4(ip: string): boolean {
    const parts = ip.split('.');
    return (
      parts.length === 4 &&
      parts.every((part) => {
        const num = parseInt(part, 10);
        return !isNaN(num) && num >= 0 && num <= 255 && part === num.toString();
      })
    );
  }

  function isIPv6(ip: string): boolean {
    const ipv6Regex =
      /^([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}$|^([0-9a-fA-F]{1,4}:){1,7}:$|^([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}$|^([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}$|^([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}$|^([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}$|^([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}$|^[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})$|^:((:[0-9a-fA-F]{1,4}){1,7}|:)$|^::$/;
    return ipv6Regex.test(ip) || /^::$/.test(ip) || /^::1$/.test(ip);
  }

  function generateRecords() {
    const hostnames = hostnameInput
      .split('\n')
      .map((h) => h.trim())
      .filter((h) => h);
    const ips = ipInput
      .split('\n')
      .map((i) => i.trim())
      .filter((i) => i);

    if (hostnames.length === 0 || ips.length === 0) {
      results = [];
      return;
    }

    const newResults: typeof results = [];
    const maxLength = Math.max(hostnames.length, ips.length);

    for (let i = 0; i < maxLength; i++) {
      const hostname = hostnames[i % hostnames.length];
      const ip = ips[i % ips.length];

      if (hostname && ip) {
        const recordType = isIPv4(ip) ? 'A' : isIPv6(ip) ? 'AAAA' : 'INVALID';
        newResults.push({
          type: recordType,
          name: hostname,
          ttl: ttl,
          value: ip,
        });
      }
    }

    results = newResults;
  }

  function generateZoneFileContent() {
    if (results.length === 0) return;

    // Generate serial number from current date
    const today = new Date();
    const serial =
      today.getFullYear().toString() +
      (today.getMonth() + 1).toString().padStart(2, '0') +
      today.getDate().toString().padStart(2, '0') +
      '01';

    const zoneHeader = `; Zone file for ${zoneName}
; Generated by ${window.location.host}
$TTL ${ttl}
$ORIGIN ${zoneName}.

@ IN SOA ns1.${zoneName}. admin.${zoneName}. (
    ${serial}        ; Serial
    3600              ; Refresh
    1800              ; Retry
    604800            ; Expire
    86400             ; Minimum TTL
)

; Name servers
@ IN NS ns1.${zoneName}.
@ IN NS ns2.${zoneName}.

; A and AAAA Records
`;

    const records = results
      .map((record) => {
        const name = record.name === '@' ? '@' : record.name;
        return `${name.padEnd(20)} IN ${record.type.padEnd(6)} ${record.value}`;
      })
      .join('\n');

    zoneFileContent = zoneHeader + records;
  }

  function loadExample(example: (typeof examples)[0]) {
    hostnameInput = example.hostnames;
    ipInput = example.ips;
    generateRecords();
  }

  function downloadZoneFile() {
    const blob = new Blob([zoneFileContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${zoneName}.zone`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function copyToClipboard(text: string) {
    navigator.clipboard.writeText(text);
  }

  // Generate records when input changes
  $effect(() => {
    generateRecords();
  });

  // Generate zone file when flag changes and records exist
  $effect(() => {
    if (generateZoneFile && results.length > 0) {
      generateZoneFileContent();
    } else {
      zoneFileContent = '';
    }
  });
</script>

<div class="card">
  <div class="card-header">
    <h1>{$t('tools/dns-aaaa-bulk.title')}</h1>
    <p class="card-subtitle">
      {$t('tools/dns-aaaa-bulk.description')}
    </p>
  </div>

  <div class="grid-layout">
    <div class="input-section">
      <div class="input-group">
        <label for="hostnames" use:tooltip={$t('tools/dns-aaaa-bulk.input.hostnames.tooltip')}>
          <Icon name="server" size="sm" />
          {$t('tools/dns-aaaa-bulk.input.hostnames.label')}
        </label>
        <textarea
          id="hostnames"
          bind:value={hostnameInput}
          placeholder={$t('tools/dns-aaaa-bulk.input.hostnames.placeholder')}
          rows="8"
        ></textarea>
      </div>

      <div class="input-group">
        <label for="ips" use:tooltip={$t('tools/dns-aaaa-bulk.input.ips.tooltip')}>
          <Icon name="networking" size="sm" />
          {$t('tools/dns-aaaa-bulk.input.ips.label')}
        </label>
        <textarea id="ips" bind:value={ipInput} placeholder={$t('tools/dns-aaaa-bulk.input.ips.placeholder')} rows="8"
        ></textarea>
      </div>

      <div class="controls-row">
        <div class="input-group">
          <label for="ttl" use:tooltip={$t('tools/dns-aaaa-bulk.input.ttl.tooltip')}>
            <Icon name="clock" size="sm" />
            {$t('tools/dns-aaaa-bulk.input.ttl.label')}
          </label>
          <input type="number" id="ttl" bind:value={ttl} min="60" max="86400" />
        </div>

        <label class="checkbox-option">
          <input type="checkbox" bind:checked={generateZoneFile} />
          <span class="checkmark"></span>
          {$t('tools/dns-aaaa-bulk.input.generateZoneFile')}
        </label>
      </div>

      {#if generateZoneFile}
        <div class="input-group">
          <label for="zoneName" use:tooltip={$t('tools/dns-aaaa-bulk.input.zoneName.tooltip')}>
            <Icon name="globe" size="sm" />
            {$t('tools/dns-aaaa-bulk.input.zoneName.label')}
          </label>
          <input
            type="text"
            id="zoneName"
            bind:value={zoneName}
            placeholder={$t('tools/dns-aaaa-bulk.input.zoneName.placeholder')}
          />
        </div>
      {/if}
    </div>

    <div class="examples-section">
      <details class="examples-toggle" bind:open={showExamples}>
        <summary>
          <Icon name="lightbulb" size="sm" />
          {$t('tools/dns-aaaa-bulk.examples.title')}
        </summary>
        <div class="examples-grid">
          {#each examples as example (example.label)}
            <button class="example-card" onclick={() => loadExample(example)}>
              <h4>{example.label}</h4>
              <p>{$t('tools/dns-aaaa-bulk.examples.hostsCount', { count: example.hostnames.split('\n').length })}</p>
            </button>
          {/each}
        </div>
      </details>
    </div>
  </div>

  {#if results.length > 0}
    <div class="results-section">
      <div class="results-header">
        <h2>{$t('tools/dns-aaaa-bulk.results.title')}</h2>
        <div class="export-buttons">
          <button
            onclick={() => copyToClipboard(results.map((r) => `${r.name} ${r.ttl} IN ${r.type} ${r.value}`).join('\n'))}
          >
            <Icon name="copy" size="sm" />
            {$t('tools/dns-aaaa-bulk.results.copyRecordsButton')}
          </button>
          {#if generateZoneFile && zoneFileContent}
            <button onclick={downloadZoneFile}>
              <Icon name="download" size="sm" />
              {$t('tools/dns-aaaa-bulk.results.downloadZoneButton')}
            </button>
          {/if}
        </div>
      </div>

      <div class="records-table">
        <div class="table-header">
          <div>{$t('tools/dns-aaaa-bulk.results.tableHeaders.name')}</div>
          <div>{$t('tools/dns-aaaa-bulk.results.tableHeaders.ttl')}</div>
          <div>{$t('tools/dns-aaaa-bulk.results.tableHeaders.type')}</div>
          <div>{$t('tools/dns-aaaa-bulk.results.tableHeaders.value')}</div>
        </div>
        {#each results as record, index (index)}
          <div class="table-row" class:invalid={record.type === 'INVALID'}>
            <div class="name">{record.name}</div>
            <div class="ttl">{record.ttl}</div>
            <div class="type">
              <span
                class="record-type"
                class:a={record.type === 'A'}
                class:aaaa={record.type === 'AAAA'}
                class:error={record.type === 'INVALID'}
              >
                {record.type}
              </span>
            </div>
            <div class="value">{record.value}</div>
          </div>
        {/each}
      </div>

      {#if generateZoneFile && zoneFileContent}
        <div class="zone-file-section">
          <div class="zone-file-header">
            <h3>{$t('tools/dns-aaaa-bulk.zoneFile.title')}</h3>
            <button onclick={() => copyToClipboard(zoneFileContent)}>
              <Icon name="copy" size="sm" />
              {$t('tools/dns-aaaa-bulk.zoneFile.copyButton')}
            </button>
          </div>
          <pre class="zone-file-content">{zoneFileContent}</pre>
        </div>
      {/if}
    </div>
  {/if}
</div>

<style lang="scss">
  .card-header {
    .card-subtitle {
      color: var(--text-secondary);
      margin-top: var(--spacing-xs);
    }
  }

  .grid-layout {
    display: grid;
    grid-template-columns: 2fr 1fr;
    gap: var(--spacing-lg);
    margin: var(--spacing-lg) 0;

    @media (max-width: 768px) {
      grid-template-columns: 1fr;
    }
  }

  .input-section {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-md);

    textarea {
      background: var(--bg-primary);
    }
  }

  .controls-row {
    display: grid;
    grid-template-columns: 1fr auto;
    gap: var(--spacing-md);
    align-items: end;
  }

  .checkbox-option {
    display: flex;
    align-items: center;
    gap: var(--spacing-xs);
    cursor: pointer;
    font-size: var(--font-size-sm);

    input[type='checkbox'] {
      display: none;
    }

    .checkmark {
      width: 18px;
      height: 18px;
      border: 2px solid var(--border-primary);
      border-radius: var(--radius-sm);
      background: var(--bg-primary);
      position: relative;
      transition: all var(--transition-fast);

      &::after {
        content: '';
        position: absolute;
        left: 5px;
        top: 2px;
        width: 6px;
        height: 10px;
        border: 2px solid var(--bg-primary);
        border-width: 0 2px 2px 0;
        transform: rotate(45deg);
        opacity: 0;
        transition: opacity var(--transition-fast);
      }
    }

    input:checked + .checkmark {
      background: var(--color-primary);
      border-color: var(--color-primary);

      &::after {
        opacity: 1;
      }
    }
  }

  .examples-section {
    .examples-toggle {
      border: 1px solid var(--border-primary);
      border-radius: var(--radius-md);
      padding: var(--spacing-md);
      background: var(--bg-secondary);

      summary {
        display: flex;
        align-items: center;
        gap: var(--spacing-xs);
        cursor: pointer;
        font-weight: 500;
        color: var(--text-primary);

        &:hover {
          color: var(--color-primary);
        }
      }
    }

    .examples-grid {
      display: grid;
      gap: var(--spacing-sm);
      margin-top: var(--spacing-md);
    }

    .example-card {
      padding: var(--spacing-sm);
      border: 1px solid var(--border-secondary);
      border-radius: var(--radius-sm);
      background: var(--bg-primary);
      cursor: pointer;
      transition: all var(--transition-fast);

      h4 {
        margin: 0 0 var(--spacing-xs) 0;
        font-size: var(--font-size-sm);
        font-weight: 600;
      }

      p {
        margin: 0;
        font-size: var(--font-size-xs);
        color: var(--text-secondary);
      }

      &:hover {
        border-color: var(--color-primary);
        background: var(--surface-hover);
      }
    }
  }

  .results-section {
    border-top: 1px solid var(--border-primary);
    padding-top: var(--spacing-lg);
  }

  .results-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: var(--spacing-md);

    h2 {
      margin: 0;
      font-size: var(--font-size-lg);
      color: var(--text-primary);
    }

    .export-buttons {
      display: flex;
      gap: var(--spacing-sm);

      button {
        display: flex;
        align-items: center;
        gap: var(--spacing-xs);
        padding: var(--spacing-sm) var(--spacing-md);
        border: 1px solid var(--border-primary);
        border-radius: var(--radius-sm);
        background: var(--bg-primary);
        color: var(--text-primary);
        font-size: var(--font-size-sm);
        cursor: pointer;
        transition: all var(--transition-fast);

        &:hover {
          background: var(--color-primary);
          color: var(--bg-primary);
          border-color: var(--color-primary);
        }
      }
    }
  }

  .records-table {
    border: 1px solid var(--border-primary);
    border-radius: var(--radius-md);
    overflow: hidden;

    .table-header {
      display: grid;
      grid-template-columns: 2fr 1fr 1fr 2fr;
      background: var(--bg-primary);
      font-weight: 600;
      font-size: var(--font-size-sm);

      > div {
        padding: var(--spacing-sm) var(--spacing-md);
        border-right: 1px solid var(--border-primary);

        &:last-child {
          border-right: none;
        }
      }
    }

    .table-row {
      display: grid;
      grid-template-columns: 2fr 1fr 1fr 2fr;
      border-top: 1px solid var(--border-secondary);

      &.invalid {
        background: rgba(var(--color-error-rgb), 0.1);
      }

      > div {
        padding: var(--spacing-sm) var(--spacing-md);
        border-right: 1px solid var(--border-secondary);
        font-size: var(--font-size-sm);

        &:last-child {
          border-right: none;
        }
      }

      .name {
        font-weight: 500;
        font-family: var(--font-mono);
      }

      .value {
        font-family: var(--font-mono);
        word-break: break-all;
      }
    }
  }

  .record-type {
    padding: 2px 6px;
    border-radius: var(--radius-sm);
    font-size: var(--font-size-xs);
    font-weight: 600;
    text-transform: uppercase;

    &.a {
      background: rgba(var(--color-success-rgb), 0.2);
      color: var(--color-success);
    }

    &.aaaa {
      background: rgba(var(--color-info-rgb), 0.2);
      color: var(--color-info);
    }

    &.error {
      background: rgba(var(--color-error-rgb), 0.2);
      color: var(--color-error);
    }
  }

  .zone-file-section {
    margin-top: var(--spacing-lg);
    border-top: 1px solid var(--border-secondary);
    padding-top: var(--spacing-lg);

    .zone-file-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: var(--spacing-md);

      h3 {
        margin: 0;
        font-size: var(--font-size-md);
        color: var(--text-primary);
      }

      button {
        display: flex;
        align-items: center;
        gap: var(--spacing-xs);
        padding: var(--spacing-sm) var(--spacing-md);
        border: 1px solid var(--border-primary);
        border-radius: var(--radius-sm);
        background: var(--bg-primary);
        color: var(--text-primary);
        font-size: var(--font-size-sm);
        cursor: pointer;
        transition: all var(--transition-fast);

        &:hover {
          background: var(--color-primary);
          color: var(--bg-primary);
          border-color: var(--color-primary);
        }
      }
    }

    .zone-file-content {
      background: var(--bg-primary);
      border: 1px solid var(--border-primary);
      border-radius: var(--radius-md);
      padding: var(--spacing-md);
      font-family: var(--font-mono);
      font-size: var(--font-size-sm);
      line-height: 1.4;
      max-height: 400px;
      overflow-y: auto;
      white-space: pre;
    }
  }
</style>
